export const ANTHROPIC_MODEL_CLAUDE_SONNET = 'claude-sonnet-4-6'
export const ANTHROPIC_MODEL_CLAUDE_OPUS = 'claude-opus-4-6'

export type AnthropicModel = typeof ANTHROPIC_MODEL_CLAUDE_SONNET | typeof ANTHROPIC_MODEL_CLAUDE_OPUS

export const ATTR_BOT_COMMAND = 'bot.command'
export const ATTR_BOT_CHAT_MODE = 'bot.chat_mode'
export const ATTR_BOT_MESSAGE_COUNT = 'bot.message_count'
export const ATTR_BOT_SESSION_ID = 'bot.session_id'
export const ATTR_BOT_PURPOSE = 'bot.purpose'
export const ATTR_BOT_PATIENT_ID = 'bot.patient_id'
export const ATTR_TELEGRAM_USER_ID = 'telegram.user_id'
export const ATTR_TELEGRAM_CHAT_ID = 'telegram.chat_id'
export const ATTR_TELEGRAM_USERNAME = 'telegram.username'
export const ATTR_SCHEDULER_CHECKIN_COUNT = 'scheduler.checkin.count'
export const ATTR_STORAGE_OPERATION = 'storage.operation'
export const ATTR_STORAGE_FILE_PATH = 'storage.file_path'
export const ATTR_TELEGRAM_SEND_PARSE_MODE = 'telegram.send.parse_mode'
export const ATTR_TELEGRAM_SEND_CHUNK_COUNT = 'telegram.send.chunk_count'
export const ATTR_TELEGRAM_SEND_FALLBACK = 'telegram.send.fallback'
